### ISSUE TITLE
Segmentation Fault when using Datetime after deinitializing a Timezone

### ISSUE THREAD

**Issue by Ratakor** [FObersteiner/zdt#32]
Minimal repro:
```zig
const std = @import("std");
const zdt = @import("zdt.zig");

pub fn main() !void {
    const date = init: {
        var tz = try zdt.Timezone.tzLocal(std.heap.page_allocator);
        const date = try zdt.Datetime.now(tz);
        tz.deinit(); // this doesn't modify date since date copy tz
        break :init date;
    };
    // date.tzinfo is not null since we initialized it with tz earlier
    std.debug.print("{any}", .{date.tzinfo.?.tzFile});
}
```
Output without stack trace:
```
lib.tzif.Tz{ .allocator = mem.Allocator{ .ptr = anyopaque@0, .vtable = mem.Allocator.VTable{ .alloc = fn (*anyopaque, usize, u8, usize) ?[*]u8@103d980, .resize = fn (*anyopaque, []u8, u8, usize, usize) bool@103db70, .free = fn (*anyopaque, []u8, u8, usize) void@103dde0 } }, .transitions = { lib.tzif.Transition{ .ts = Segmentation fault at address 0x702d5cd6f000
```

Datetime should either take a ptr to Timezone or make a deep copy of the one passed in argument.

**Comment by FObersteiner** [comment]
Thanks for pointing this out. TBH, I'm not 100% happy with how the tz field is currently handled. I already have "re-visit: ptr to TZ" on my list for that reason. Bugs like this one underline this. The reason why I "have it on the list" and not fixed is that when parsing UTC offsets, a pointer type tz would require an allocator if I'm not mistaken. On the other hand, making a deep copy would require both the Timezone struct *and* the Datetime to be deinitialized, no?

**Comment by Ratakor** [comment]
> when parsing UTC offsets, a pointer type tz would require an allocator if I'm not mistaken 
I can't seem to find where an allocator would be required when we already have a timezone, could you point it to me please.

> making a deep copy would require both the Timezone struct and the Datetime to be deinitialized, no?
Yes and I think it's a really bad idea to add a deinit function to Datetime.

**Comment by FObersteiner** [comment]
I was referring to this part: https://github.com/FObersteiner/zdt/blob/662434a363e05d65d73623749e7a4b2f31189aa4/lib/string.zig#L294

At the moment, the UTC offset is part of the `Timezone`. If the parser function creates a Timezone from an offset part of a string, resulting Timezone variable is local to the parser function; if I use a pointer to that, that pointer points to temporary memory from the caller's point of view I think. There might be a better way to handle such offsets, but I'll have to give this some more though.

There might be another issue here. We have an optional field (tzinfo); once this field is set (non-null), de-initializing the value would leave undefined behavior (which segfaults), no matter if the value is a pointer or not. Maybe (hopefully?) I have a misunderstanding there, but as it stands, using a pointer to a Timezone looks like replacing one footgun with another. Again, some more thought needed...

**Comment by Ratakor** [comment]
Can Timezone.tzFile and Timezone.tzOffset be set and used on the same Timezone or does the library set one and discard the other based on some precedence? From what I've seen I think we could merge tzFile and tzOffset into a union or a polymorphic type with @fieldParentPtr, this could probably solve this issue and make Timezone and Datetime structs consume less memory.

**Comment by FObersteiner** [comment]
`tzFile` is the set of rules, if you load one of the IANA identifiers. `tzOffset` gets calculated for any datetime once you attach a Timezone to it (specify it as tzinfo field in `Datetime.fromFields`, use `tzLocalize` etc.). So while tzOffset is specific to a datetime, tzFile is not. From that perspective, it might make sense to have the offset as a field of the datetime struct (default to zero; doesn't even have to be optional*), and the tzFile or "tzRuleset" as a pointer. This would also make more sense since many datetimes can share the same tzRuleset while this could imply different offsets, depending on the actual date. And it would save memory of course.

---

*) - giving a non-optional offset from UTC to any datetime would mean to me that there is no "naive" datetime, i.e. a datetime that does not "know" where it belongs. This is something that doesn't sound too bad to me...

**Comment by FObersteiner** [comment]
marking this as completed in 4d014a5b030232d76e8181fb0b06f4871c56c1ef - note that the API has changed quite a bit. I'm not claiming it's footgun-free now, but at least it shouldn't segfault that easily.

**Comment by Ratakor** [comment]
Nice thank you very much!

By the way why is there a constCast() in Timezone.deinit, I think it should take a *Timezone instead to prevent from very rare segfault like in the snippet below.
```zig
const zdt = @import("zdt.zig");
pub fn main() void {
    const tz: zdt.Timezone = .{ .rules = .{ .utc = .{} } };
    tz.deinit();
}
```

**Comment by FObersteiner** [comment]
Right, that construct seems a bit weird. `deinit` takes a *const because that allows the Timezone you declare to be a const - which prevents another footgun where you create a Timezone, set it to a Datetime, de-initialize it, and overwrite it with a new one. Then the Datetime would have a pointer to the "new" Timezone but the offset would be wrong (that of the first Timezone instance ).

Anyways, I will have a look at the new issue you describe above tomorrow.
