### ISSUE TITLE
Add a comptime version of string.TokenizeAndPrint

### ISSUE THREAD

**Issue by Ratakor** [FObersteiner/zdt#38]
Provide an API to specify comptime directives e.g.
```zig
pub fn tokenizeAndPrintComptime(dt: *const Datetime, comptime directives: []const u8, writer: anytype) @TypeOf(writer).Error!void { ... }
```
This will remove the overhead of parsing the directive at runtime and replace InvalidFormat errors with `@compileError`.
The annoying part about implementing it is that it can produce a lot of code duplication.

**Comment by Ratakor** [comment]
It's probably better to just have a runtime API. The overhead shouldn't be that big even when called a lot of time.

**Comment by FObersteiner** [comment]
> It's probably better to just have a runtime API.

At the moment yes. In general, I think this is a good suggestion, to keep this possibility in mind at least. So thanks for bringing it up.

The previous version of the parser actually had a comptime parameter for the directives string + an inlined for loop for iterating the directives / parsing. But otherwise, it was hard to read and even harder to modify without braking it IMHO. For the new version, my idea was to have a runtime API and focus on features (esp. the modifier character for instance). I did a limited number of benchmarks and the runtime-version overhead is significant in a relative comparison (as expected). It comes down to a trade-off between features/maintainability and performance I guess. Since I never went for high-end performance with this ("blazingly fast", as they write everywhere nowadays), the current version is OK I think.

Let's pick up this topic again when Zig 0.14 stable is released. I wanted to have another look at labeled switches then anyways.
